/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c EngModeIf -p EngModeIf.h:EngModeIf.cpp com.lge.car.eng.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */


#ifdef __ENG_MODE__

#include "EngModeIf.h"

/*
 * Implementation of interface class EngModeIf
 */

EngModeIf::EngModeIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

EngModeIf::~EngModeIf()
{
}

#endif //__ENG_MODE__
