#ifndef DHAVN_APPFILEMANAGER_COMMONDEF_H
#define DHAVN_APPFILEMANAGER_COMMONDEF_H

#include <QObject>
#include <uistate_manager_def.h>

class CommonDef : public QObject
{
   Q_OBJECT
   Q_ENUMS( FileTypes JOG_DIRECTIONS )
   Q_ENUMS( FILEMANAGER_EVT_KEY_STATUS_T )
   Q_ENUMS( FILEMANAGER_DISPLAY_T )
   Q_ENUMS( FILEMANAGER_EVT_KEY_T )

public:
   enum FileTypes
   {
      MusicFileType,
      VideoFileType,
      PictureFileType
   };

   enum JOG_DIRECTIONS
   {
      JOG_DIRECTION_UP,
      JOG_DIRECTION_RIGHT,
      JOG_DIRECTION_DOWN,
      JOG_DIRECTION_LEFT,
      JOG_DIRECTION_SCROLL_RIGHT,
      JOG_DIRECTION_SCROLL_LEFT,
      JOG_DIRECTION_CENTER
   };

   enum FILEMANAGER_EVT_KEY_STATUS_T
   {
      FILEMANAGER_EVT_KEY_STATUS_PRESSED = KEY_STATUS_PRESSED,
      FILEMANAGER_EVT_KEY_STATUS_RELEASED = KEY_STATUS_RELEASED
   };

   enum FILEMANAGER_DISPLAY_T
   {
      FILEMANAGER_DISPLAY_FRONT,
      FILEMANAGER_DISPLAY_REAR,
      FILEMANAGER_DISPLAY_NONE
   };

   enum FILEMANAGER_EVT_KEY_T
   {
      FILEMANAGER_EVT_KEY_BACK,
      FILEMANAGER_EVT_KEY_MENU
   };
};

#endif // DHAVN_APPFILEMANAGER_COMMONDEF_H
