/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a dab_adaptor -c DABAdaptor com.lge.car.micom.dab.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dab_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DABAdaptor
 */

DABAdaptor::DABAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DABAdaptor::~DABAdaptor()
{
    // destructor
}

void DABAdaptor::LgeDBus_DABPICodeRequest(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.dab.LgeDBus_DABPICodeRequest
    QMetaObject::invokeMethod(parent(), "LgeDBus_DABPICodeRequest", Q_ARG(QByteArray, in0));
}

void DABAdaptor::LgeDBus_DABTAStatus(uchar in0)
{
    // handle method call com.lge.car.micom.dab.LgeDBus_DABTAStatus
    QMetaObject::invokeMethod(parent(), "LgeDBus_DABTAStatus", Q_ARG(uchar, in0));
}

