/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a sysinfo_adaptor -c SysInfoAdaptor com.lge.car.micom.sysinfo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "sysinfo_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SysInfoAdaptor
 */

SysInfoAdaptor::SysInfoAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SysInfoAdaptor::~SysInfoAdaptor()
{
    // destructor
}

QByteArray SysInfoAdaptor::LgeDBus_AskAMPVersion()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskAMPVersion
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskAMPVersion", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskBTMACAddr()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskBTMACAddr
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskBTMACAddr", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskHDRadioVersion()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskHDRadioVersion
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskHDRadioVersion", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskLanguageInfoValue()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskLanguageInfoValue
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskLanguageInfoValue", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskMOST_INICVersion()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskMOST_INICVersion
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskMOST_INICVersion", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskSettingValueMsg()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskSettingValueMsg
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskSettingValueMsg", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskSysBootType()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskSysBootType
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskSysBootType", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskSysLastStatus()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskSysLastStatus
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskSysLastStatus", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskSysOption()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskSysOption
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskSysOption", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray SysInfoAdaptor::LgeDBus_AskSysVersion()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_AskSysVersion
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskSysVersion", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

void SysInfoAdaptor::LgeDBus_BTMACAddrStore(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_BTMACAddrStore
    QMetaObject::invokeMethod(parent(), "LgeDBus_BTMACAddrStore", Q_ARG(QByteArray, in0));
}

void SysInfoAdaptor::LgeDBus_CPUAliveMsg()
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_CPUAliveMsg
    QMetaObject::invokeMethod(parent(), "LgeDBus_CPUAliveMsg");
}

void SysInfoAdaptor::LgeDBus_EmergencyConditionMsg(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_EmergencyConditionMsg
    QMetaObject::invokeMethod(parent(), "LgeDBus_EmergencyConditionMsg", Q_ARG(QByteArray, in0));
}

void SysInfoAdaptor::LgeDBus_EtcGUIMode(uchar in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_EtcGUIMode
    QMetaObject::invokeMethod(parent(), "LgeDBus_EtcGUIMode", Q_ARG(uchar, in0));
}

void SysInfoAdaptor::LgeDBus_SetLanguageInfo(uchar in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_SetLanguageInfo
    QMetaObject::invokeMethod(parent(), "LgeDBus_SetLanguageInfo", Q_ARG(uchar, in0));
}

void SysInfoAdaptor::LgeDBus_SetSysOption(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_SetSysOption
    QMetaObject::invokeMethod(parent(), "LgeDBus_SetSysOption", Q_ARG(QByteArray, in0));
}

void SysInfoAdaptor::LgeDBus_SettingValueStatusMsg(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_SettingValueStatusMsg
    QMetaObject::invokeMethod(parent(), "LgeDBus_SettingValueStatusMsg", Q_ARG(QByteArray, in0));
}

void SysInfoAdaptor::LgeDBus_SwVersionMsg(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.sysinfo.LgeDBus_SwVersionMsg
    QMetaObject::invokeMethod(parent(), "LgeDBus_SwVersionMsg", Q_ARG(QByteArray, in0));
}

