/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a tmc_adaptor -c TMCAdaptor com.lge.car.micom.tmc.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "tmc_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TMCAdaptor
 */

TMCAdaptor::TMCAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TMCAdaptor::~TMCAdaptor()
{
    // destructor
}

QByteArray TMCAdaptor::LgeDBus_AskCurrentFreq()
{
    // handle method call com.lge.car.micom.tmc.LgeDBus_AskCurrentFreq
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskCurrentFreq", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray TMCAdaptor::LgeDBus_AskStationList()
{
    // handle method call com.lge.car.micom.tmc.LgeDBus_AskStationList
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskStationList", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

QByteArray TMCAdaptor::LgeDBus_AskStationSensitivity()
{
    // handle method call com.lge.car.micom.tmc.LgeDBus_AskStationSensitivity
    QByteArray out0;
    QMetaObject::invokeMethod(parent(), "LgeDBus_AskStationSensitivity", Q_RETURN_ARG(QByteArray, out0));
    return out0;
}

void TMCAdaptor::LgeDBus_SetCountryCodeAndDecodeStatus(const QByteArray &in0)
{
    // handle method call com.lge.car.micom.tmc.LgeDBus_SetCountryCodeAndDecodeStatus
    QMetaObject::invokeMethod(parent(), "LgeDBus_SetCountryCodeAndDecodeStatus", Q_ARG(QByteArray, in0));
}

void TMCAdaptor::LgeDBus_SetManualFreqChange(uchar in0, uchar in1)
{
    // handle method call com.lge.car.micom.tmc.LgeDBus_SetManualFreqChange
    QMetaObject::invokeMethod(parent(), "LgeDBus_SetManualFreqChange", Q_ARG(uchar, in0), Q_ARG(uchar, in1));
}

