/****************************************************************************
** Meta object code from reading C++ file 'DHAVN_AppHomeScreen_Def_Private.h'
**
** Created by: The Qt Meta Object Compiler version 63 (Qt 4.8.3)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "hdr/DHAVN_AppHomeScreen_Def_Private.h"
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'DHAVN_AppHomeScreen_Def_Private.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 63
#error "This file was generated using the moc from 4.8.3. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
static const uint qt_meta_data_HSDefP[] = {

 // content:
       6,       // revision
       0,       // classname
       0,    0, // classinfo
       0,    0, // methods
       0,    0, // properties
       9,   14, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // enums: name, flags, count, data
       7, 0x0,   13,   50,
      17, 0x0,   78,   76,
      28, 0x0,   58,  232,
      37, 0x0,   85,  348,
      43, 0x0,   14,  518,
      51, 0x0,    7,  546,
      61, 0x0,    8,  560,
      68, 0x0,    2,  576,
      82, 0x0,   22,  580,

 // enum data: key, value
      95, uint(HSDefP::VIEW_ID_MAIN),
     108, uint(HSDefP::VIEW_ID_MEDIA),
     122, uint(HSDefP::VIEW_ID_SETTINGS),
     139, uint(HSDefP::VIEW_ID_SETTINGS_GENERAL),
     164, uint(HSDefP::VIEW_ID_BLUELINK),
     181, uint(HSDefP::VIEW_ID_BLUELINK_PHONE),
     204, uint(HSDefP::VIEW_ID_APPS),
     217, uint(HSDefP::VIEW_ID_INFO),
     230, uint(HSDefP::VIEW_ID_ENGINEERING_FULL),
     255, uint(HSDefP::VIEW_ID_ENGINEERING_SIMPLE),
     282, uint(HSDefP::VIEW_ID_ENGINEERING_DYNAMICS),
     311, uint(HSDefP::VIEW_ID_MAX),
     323, uint(HSDefP::VIEW_ID_INVALID),
     339, uint(HSDefP::APP_DATA_INVALID),
     356, uint(HSDefP::APP_DATA_STRING_MINIMUM),
     380, uint(HSDefP::APP_DATA_AUDIO_USB1_TEXT),
     405, uint(HSDefP::APP_DATA_AUDIO_USB2_TEXT),
     430, uint(HSDefP::APP_DATA_VIDEO_USB1_TEXT),
     455, uint(HSDefP::APP_DATA_VIDEO_USB2_TEXT),
     480, uint(HSDefP::APP_DATA_PHOTO_USB1_TEXT),
     505, uint(HSDefP::APP_DATA_PHOTO_USB2_TEXT),
     530, uint(HSDefP::APP_DATA_IPOD1_TEXT),
     550, uint(HSDefP::APP_DATA_IPOD2_TEXT),
     570, uint(HSDefP::APP_DATA_STRING_MAXIMUM),
     594, uint(HSDefP::APP_DATA_AVAILABLE_MINIMUM),
     621, uint(HSDefP::APP_DATA_AVAILABLE_NAVI),
     645, uint(HSDefP::APP_DATA_AVAILABLE_DAB),
     668, uint(HSDefP::APP_DATA_AVAILABLR_MEDIA),
     693, uint(HSDefP::APP_DATA_AVAILABLE_JBOX),
     717, uint(HSDefP::APP_DATA_AVAILABLE_JBOX_VIDEO),
     747, uint(HSDefP::APP_DATA_AVAILABLE_JBOX_AUIDIO),
     778, uint(HSDefP::APP_DATA_AVAILABLE_JBOX_IMAGE),
     808, uint(HSDefP::APP_DATA_AVAILABLE_USB1),
     832, uint(HSDefP::APP_DATA_AVAILABLE_USB1_VIDEO),
     862, uint(HSDefP::APP_DATA_AVAILABLE_USB1_AUDIO),
     892, uint(HSDefP::APP_DATA_AVAILABLE_USB1_IMAGE),
     922, uint(HSDefP::APP_DATA_AVAILABLE_USB2),
     946, uint(HSDefP::APP_DATA_AVAILABLE_USB2_VIDEO),
     976, uint(HSDefP::APP_DATA_AVAILABLE_USB2_AUDIO),
    1006, uint(HSDefP::APP_DATA_AVAILABLE_USB2_IMAGE),
    1036, uint(HSDefP::APP_DATA_AVAILABLE_DISC),
    1060, uint(HSDefP::APP_DATA_AVAILABLE_DISC_DVD_VIDEO),
    1094, uint(HSDefP::APP_DATA_AVAILABLE_DISC_VCD),
    1122, uint(HSDefP::APP_DATA_AVAILABLE_DISC_DVD_AUDIO),
    1156, uint(HSDefP::APP_DATA_AVAILABLE_DISC_MP3),
    1184, uint(HSDefP::APP_DATA_AVAILABLE_DISC_CD),
    1211, uint(HSDefP::APP_DATA_AVAILABLE_IPOD1),
    1236, uint(HSDefP::APP_DATA_AVAILABLE_IPOD2),
    1261, uint(HSDefP::APP_DATA_AVAILABLE_AUX),
    1284, uint(HSDefP::APP_DATA_AVAILABLE_BT),
    1306, uint(HSDefP::APP_DATA_AVAILABLE_BT_PANDORA),
    1336, uint(HSDefP::APP_DATA_AVAILABLE_BT_AHA),
    1362, uint(HSDefP::APP_DATA_AVAILABLE_IBOX_MODEM),
    1392, uint(HSDefP::APP_DATA_AVAILABLE_PANDORA1),
    1420, uint(HSDefP::APP_DATA_AVAILABLE_PANDORA2),
    1448, uint(HSDefP::APP_DATA_AVAILABLE_AHA1),
    1472, uint(HSDefP::APP_DATA_AVAILABLE_AHA2),
    1496, uint(HSDefP::APP_DATA_AVAILABLE_MAXIMUM),
    1523, uint(HSDefP::APP_DATA_ENABLED_MINIMUM),
    1548, uint(HSDefP::APP_DATA_ENABLED_NAVI),
    1570, uint(HSDefP::APP_DATA_ENABLED_MEDIA),
    1593, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO),
    1622, uint(HSDefP::APP_DATA_ENABLED_MEDIA_PHOTO),
    1651, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO),
    1680, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO_JBOX),
    1714, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO_USB1),
    1748, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO_USB2),
    1782, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO_DISC),
    1816, uint(HSDefP::APP_DATA_ENABLED_MEDIA_VIDEO_AUX),
    1849, uint(HSDefP::APP_DATA_ENABLED_MEDIA_PHOTO_JBOX),
    1883, uint(HSDefP::APP_DATA_ENABLED_MEDIA_PHOTO_USB1),
    1917, uint(HSDefP::APP_DATA_ENABLED_MEDIA_PHOTO_USB2),
    1951, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_JBOX),
    1985, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_USB1),
    2019, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_USB2),
    2053, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_DISC),
    2087, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_IPOD1),
    2122, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_IPOD2),
    2157, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_AUX),
    2190, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_BT),
    2222, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_PANDORA),
    2259, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUDIO_AHA),
    2292, uint(HSDefP::APP_DATA_ENABLED_MEDIA_AUX),
    2319, uint(HSDefP::APP_DATA_ENABLED_DRIVING_MODE),
    2349, uint(HSDefP::APP_DATA_ENABLED_VR),
    2369, uint(HSDefP::APP_DATA_ENABLED_HELP),
    2391, uint(HSDefP::APP_DATA_ENABLED_PARKED),
    2415, uint(HSDefP::APP_DATA_ENABLED_MAXIMUM),
    2440, uint(HSDefP::APP_DATA_INT_MINIMUM),
    2461, uint(HSDefP::APP_DATA_INT_MAXIMUM),
    2482, uint(HSDefP::APP_DATA_MAX),
    2495, uint(HSDefP::APP_ID_NAVI),
    2507, uint(HSDefP::APP_ID_RADIO),
    2520, uint(HSDefP::APP_ID_SIRIUS_XM_FROM_HOME),
    2547, uint(HSDefP::APP_ID_DMB),
    2558, uint(HSDefP::APP_ID_BT_PHONE),
    2574, uint(HSDefP::APP_ID_AUX),
    2585, uint(HSDefP::APP_ID_AUDIO_JBOX),
    2603, uint(HSDefP::APP_ID_AUDIO_USB1),
    2621, uint(HSDefP::APP_ID_AUDIO_USB2),
    2639, uint(HSDefP::APP_ID_AUDIO_IPOD1),
    2658, uint(HSDefP::APP_ID_AUDIO_IPOD2),
    2677, uint(HSDefP::APP_ID_AUDIO_DISC),
    2695, uint(HSDefP::APP_ID_AUDIO_BLUETOOTH),
    2718, uint(HSDefP::APP_ID_PANDORA1),
    2734, uint(HSDefP::APP_ID_PANDORA2),
    2750, uint(HSDefP::APP_ID_AHA1),
    2762, uint(HSDefP::APP_ID_AHA2),
    2774, uint(HSDefP::APP_ID_BT_PANDORA),
    2792, uint(HSDefP::APP_ID_BT_AHA),
    2806, uint(HSDefP::APP_ID_VIDEO_JBOX),
    2824, uint(HSDefP::APP_ID_VIDEO_USB1),
    2842, uint(HSDefP::APP_ID_VIDEO_USB2),
    2860, uint(HSDefP::APP_ID_VIDEO_DISC),
    2878, uint(HSDefP::APP_ID_PHOTO_JBOX),
    2896, uint(HSDefP::APP_ID_PHOTO_USB1),
    2914, uint(HSDefP::APP_ID_PHOTO_USB2),
    2932, uint(HSDefP::APP_ID_SETTINGS_SOUND),
    2954, uint(HSDefP::APP_ID_SETTINGS_SCREEN),
    2977, uint(HSDefP::APP_ID_SETTINGS_NAVI),
    2998, uint(HSDefP::APP_ID_SETTINGS_BLUETOOTH),
    3024, uint(HSDefP::APP_ID_SETTINGS_VR),
    3043, uint(HSDefP::APP_ID_SETTINGS_CLOCK),
    3065, uint(HSDefP::APP_ID_WIFI_SETTINGS),
    3086, uint(HSDefP::APP_ID_SETTINGS_GENERAL_INITIALIZATION),
    3125, uint(HSDefP::APP_ID_SETTINGS_GENERAL_VIDEO_MNGMNT),
    3162, uint(HSDefP::APP_ID_SETTINGS_GENERAL_SYSTEM),
    3193, uint(HSDefP::APP_ID_SETTINGS_GENERAL_BASIC),
    3223, uint(HSDefP::APP_ID_DOWNLOAD_APP),
    3243, uint(HSDefP::APP_ID_APP_STORE),
    3260, uint(HSDefP::APP_ID_XM_DATA),
    3275, uint(HSDefP::APP_ID_VIDEO_QUICK_GUIDE),
    3300, uint(HSDefP::APP_ID_E_MANUAL),
    3316, uint(HSDefP::APP_ID_BLUELINK_PHONE),
    3338, uint(HSDefP::APP_ID_BLUELINK_ASSISTANT),
    3364, uint(HSDefP::APP_ID_BLUELINK_SETTINGS),
    3389, uint(HSDefP::APP_ID_DRIVING_INFO),
    3409, uint(HSDefP::APP_ID_SEND_TO_CAR),
    3428, uint(HSDefP::APP_ID_DAILY_ROUTE_GUIDANCE),
    3456, uint(HSDefP::APP_ID_VEHICLE_DIAGNOSTICS),
    3483, uint(HSDefP::APP_ID_SCHEDULED_DIAGNOSTICS),
    3512, uint(HSDefP::APP_ID_MAINTENANCE),
    3531, uint(HSDefP::APP_ID_BLUELINK_CENTER),
    3554, uint(HSDefP::APP_ID_MODEM_PHONE_MAIN),
    3578, uint(HSDefP::APP_ID_MODEM_DIAL),
    3596, uint(HSDefP::APP_ID_MODEM_PHONEBOOK),
    3619, uint(HSDefP::APP_ID_MODEM_CALL_HISTORY),
    3645, uint(HSDefP::APP_ID_MAX),
    3656, uint(HSDefP::APP_ID_INVALID),
    3671, uint(HSDefP::IMG_NONE),
    3680, uint(HSDefP::IMG_BG_MAIN),
    3692, uint(HSDefP::IMG_ICON_APPLICATION),
    3713, uint(HSDefP::IMG_ICON_AUX),
    3726, uint(HSDefP::IMG_ICON_BLUELINK),
    3744, uint(HSDefP::IMG_ICON_BLUELINK_ASSISTANT),
    3772, uint(HSDefP::IMG_ICON_BLUELINK_CENTER),
    3797, uint(HSDefP::IMG_ICON_BLUELINK_PHONE),
    3821, uint(HSDefP::IMG_ICON_BLUELINK_SETTINGS),
    3848, uint(HSDefP::IMG_ICON_BLUELINK_PHONE_DIAL),
    3877, uint(HSDefP::IMG_ICON_BLUETOOTH),
    3896, uint(HSDefP::IMG_ICON_BT),
    3908, uint(HSDefP::IMG_ICON_BT_PANDORA),
    3928, uint(HSDefP::IMG_ICON_BT_AHA),
    3944, uint(HSDefP::IMG_ICON_BT_SET),
    3960, uint(HSDefP::IMG_ICON_DISC),
    3974, uint(HSDefP::IMG_ICON_DMB),
    3987, uint(HSDefP::IMG_ICON_DRIVING_INFO),
    4009, uint(HSDefP::IMG_ICON_E_MANUAL),
    4027, uint(HSDefP::IMG_ICON_GENERAL),
    4044, uint(HSDefP::IMG_ICON_INFO),
    4058, uint(HSDefP::IMG_ICON_VIDEO_QUICK_GUIDE),
    4085, uint(HSDefP::IMG_ICON_JBOX),
    4099, uint(HSDefP::IMG_ICON_MEDIA),
    4114, uint(HSDefP::IMG_ICON_NAVI),
    4128, uint(HSDefP::IMG_ICON_NETWORK),
    4145, uint(HSDefP::IMG_ICON_PANDORA),
    4162, uint(HSDefP::IMG_ICON_RADIO),
    4177, uint(HSDefP::IMG_ICON_SCREEN),
    4193, uint(HSDefP::IMG_ICON_SEND_TO_CAR),
    4214, uint(HSDefP::IMG_ICON_SETTING),
    4231, uint(HSDefP::IMG_ICON_SOUND),
    4246, uint(HSDefP::IMG_ICON_SYSTEM),
    4262, uint(HSDefP::IMG_ICON_USB),
    4275, uint(HSDefP::IMG_ICON_VEHICLE_DIAGNOSTICS),
    4304, uint(HSDefP::IMG_ICON_VOIREC),
    4320, uint(HSDefP::IMG_ICON_XM),
    4332, uint(HSDefP::IMG_ICON_XM_DATA),
    4349, uint(HSDefP::IMG_ICON_AUDIO_JUKEBOX),
    4372, uint(HSDefP::IMG_ICON_AUDIO_USB),
    4391, uint(HSDefP::IMG_ICON_PHOTO_USB),
    4410, uint(HSDefP::IMG_ICON_PHOTO_JUKEBOX),
    4433, uint(HSDefP::IMG_ICON_VIDEO_USB),
    4452, uint(HSDefP::IMG_ICON_VIDEO_JUKEBOX),
    4475, uint(HSDefP::IMG_TITLE_BG),
    4488, uint(HSDefP::IMG_TITLE_BTN),
    4502, uint(HSDefP::IMG_ICON_AHA),
    4515, uint(HSDefP::IMG_ICON_IPOD),
    4529, uint(HSDefP::IMG_ICON_CLOCK),
    4544, uint(HSDefP::IMG_ICON_NAVI_SETTING),
    4566, uint(HSDefP::IMG_ICON_MAIN_PHONE_180),
    4590, uint(HSDefP::IMG_ICON_MAIN_PHONE_196),
    4614, uint(HSDefP::IMG_ICON_MAIN_PHONE_226),
    4638, uint(HSDefP::IMG_ICON_MAIN_PHONE_250),
    4662, uint(HSDefP::IMG_ICON_MAIN_APPS_180),
    4685, uint(HSDefP::IMG_ICON_MAIN_BLUELINK_180),
    4712, uint(HSDefP::IMG_ICON_MAIN_SETTING_180),
    4738, uint(HSDefP::IMG_ICON_MAIN_SETTING_196),
    4764, uint(HSDefP::IMG_ICON_MAIN_SETTING_232),
    4790, uint(HSDefP::IMG_ICON_MAIN_SETTING_238),
    4816, uint(HSDefP::IMG_ICON_MAIN_MEDIA_180),
    4840, uint(HSDefP::IMG_ICON_MAIN_MEDIA_196),
    4864, uint(HSDefP::IMG_ICON_MAIN_MEDIA_226),
    4888, uint(HSDefP::IMG_ICON_MAIN_MEDIA_234),
    4912, uint(HSDefP::IMG_ICON_MAIN_MEDIA_246),
    4936, uint(HSDefP::IMG_ICON_MAIN_MEDIA_250),
    4960, uint(HSDefP::IMG_ICON_MAIN_MEDIA_270),
    4984, uint(HSDefP::IMG_ICON_MAIN_DMB_234),
    5006, uint(HSDefP::IMG_ICON_MAIN_DMB_246),
    5028, uint(HSDefP::IMG_ICON_MAIN_RADIO_232),
    5052, uint(HSDefP::IMG_ICON_MAIN_RADIO_234),
    5076, uint(HSDefP::IMG_ICON_MAIN_RADIO_238),
    5100, uint(HSDefP::IMG_ICON_MAIN_RADIO_246),
    5124, uint(HSDefP::IMG_ICON_MAIN_RADIO_250),
    5148, uint(HSDefP::IMG_ICON_MAIN_RADIO_270),
    5172, uint(HSDefP::IMG_ICON_MAIN_NAVI_226),
    5195, uint(HSDefP::IMG_ICON_MAIN_NAVI_232),
    5218, uint(HSDefP::IMG_ICON_MAIN_NAVI_234),
    5241, uint(HSDefP::IMG_ICON_MAIN_NAVI_246),
    5264, uint(HSDefP::IMG_ICON_MAIN_XM_DATA_180),
    5290, uint(HSDefP::IMG_ICON_MAIN_XM_DATA_226),
    5316, uint(HSDefP::IMG_ICON_MAIN_XM_234),
    5337, uint(HSDefP::IMG_ICON_MAIN_XM_246),
    5358, uint(HSDefP::IMG_ICON_MAIN_XM_254),
    5379, uint(HSDefP::IMG_MAX),
    5387, uint(HSDefP::COLOR_BLACK),
    5399, uint(HSDefP::COLOR_BRIGHT_GREY),
    5417, uint(HSDefP::COLOR_SUB_TEXT_GREY),
    5437, uint(HSDefP::COLOR_GREY),
    5448, uint(HSDefP::COLOR_DIMMED_GREY),
    5466, uint(HSDefP::COLOR_DISABLE_GREY),
    5485, uint(HSDefP::COLOR_FOCUS_GREY),
    5502, uint(HSDefP::COLOR_BUTTON_GREY),
    5520, uint(HSDefP::COLOR_PROGRESS_BLUE),
    5540, uint(HSDefP::COLOR_DIMMED_BLUE),
    5558, uint(HSDefP::COLOR_128_191_255),
    5576, uint(HSDefP::COLOR_112_112_112),
    5594, uint(HSDefP::COLOR_41_41_41),
    5609, uint(HSDefP::COLOR_MAX),
    5619, uint(HSDefP::AV_TEXT_PIXEL_SIZE),
    5638, uint(HSDefP::AV_TEXT_WIDTH),
    5652, uint(HSDefP::AV_LINE1_COLOR),
    5667, uint(HSDefP::AV_LINE2_COLOR),
    5682, uint(HSDefP::AV_LINE_LO),
    5693, uint(HSDefP::AV_LINE2_VCO),
    5706, uint(HSDefP::AV_LINE1_VCO),
    5719, uint(HSDefP::ICON_TEXT_WIDTH),
    5735, uint(HSDefP::ICON_TEXT_SINGLE_VCM),
    5756, uint(HSDefP::ICON_TEXT_DOUBLE_FIRST_VCM),
    5783, uint(HSDefP::ICON_TEXT_DOUBLE_SECOND_VCM),
    5811, uint(HSDefP::ICON_TEXT_PIXEL_SIZE),
    5832, uint(HSDefP::ICON_TEXT_COLOR_NORMAL),
    5855, uint(HSDefP::ICON_TEXT_COLOR_PRESSED),
    5879, uint(HSDefP::ICON_TEXT_COLOR_DISABLED),
    5904, uint(HSDefP::FOCUS_INDEX_ICONS_MENU),
    5927, uint(HSDefP::FOCUS_INDEX_POPUP),
    5945, uint(HSDefP::POPUP_INVALID),
    5959, uint(HSDefP::POPUP_NO_MEDIA),
    5974, uint(HSDefP::POPUP_NO_IMAGE),
    5989, uint(HSDefP::POPUP_VR_NOT_SUPPORT),
    6010, uint(HSDefP::POPUP_NO_SDCARD),
    6026, uint(HSDefP::POPUP_SDCARD_NOT_SUPPORT_PREMIUM20),
    6061, uint(HSDefP::POPUP_NO_IMAGE_IN_USB),
    6083, uint(HSDefP::POPUP_NO_IMAGE_IN_JBOX),
    6106, uint(HSDefP::POPUP_NO_MUSIC),
    6121, uint(HSDefP::POPUP_NO_MUSIC_IN_USB),
    6143, uint(HSDefP::POPUP_NO_MUSIC_IN_JBOX),
    6166, uint(HSDefP::POPUP_NO_VIDEO),
    6181, uint(HSDefP::POPUP_NO_VIDEO_IN_USB),
    6203, uint(HSDefP::POPUP_NO_VIDEO_IN_JBOX),
    6226, uint(HSDefP::POPUP_RESTRICTION),
    6244, uint(HSDefP::POPUP_NO_PHONE_CONNECTED),
    6269, uint(HSDefP::POPUP_NOT_USE_BLUELINK_PHONE),
    6298, uint(HSDefP::POPUP_LOCAL_IGN),
    6314, uint(HSDefP::POPUP_LOCAL_BLUELINK),
    6335, uint(HSDefP::POPUP_LOCAL_DRS),
    6351, uint(HSDefP::POPUP_DISABLE_BT_MUSIC),
    6374, uint(HSDefP::POPUP_HELP_NOT_SUPPORT),

       0        // eod
};

static const char qt_meta_stringdata_HSDefP[] = {
    "HSDefP\0VIEW_ID_T\0APP_DATA_T\0APP_ID_T\0"
    "IMG_T\0COLOR_T\0AV_WIDGET\0ICON_T\0"
    "FOCUS_INDEX_T\0POPUP_TYPE_T\0VIEW_ID_MAIN\0"
    "VIEW_ID_MEDIA\0VIEW_ID_SETTINGS\0"
    "VIEW_ID_SETTINGS_GENERAL\0VIEW_ID_BLUELINK\0"
    "VIEW_ID_BLUELINK_PHONE\0VIEW_ID_APPS\0"
    "VIEW_ID_INFO\0VIEW_ID_ENGINEERING_FULL\0"
    "VIEW_ID_ENGINEERING_SIMPLE\0"
    "VIEW_ID_ENGINEERING_DYNAMICS\0VIEW_ID_MAX\0"
    "VIEW_ID_INVALID\0APP_DATA_INVALID\0"
    "APP_DATA_STRING_MINIMUM\0"
    "APP_DATA_AUDIO_USB1_TEXT\0"
    "APP_DATA_AUDIO_USB2_TEXT\0"
    "APP_DATA_VIDEO_USB1_TEXT\0"
    "APP_DATA_VIDEO_USB2_TEXT\0"
    "APP_DATA_PHOTO_USB1_TEXT\0"
    "APP_DATA_PHOTO_USB2_TEXT\0APP_DATA_IPOD1_TEXT\0"
    "APP_DATA_IPOD2_TEXT\0APP_DATA_STRING_MAXIMUM\0"
    "APP_DATA_AVAILABLE_MINIMUM\0"
    "APP_DATA_AVAILABLE_NAVI\0APP_DATA_AVAILABLE_DAB\0"
    "APP_DATA_AVAILABLR_MEDIA\0"
    "APP_DATA_AVAILABLE_JBOX\0"
    "APP_DATA_AVAILABLE_JBOX_VIDEO\0"
    "APP_DATA_AVAILABLE_JBOX_AUIDIO\0"
    "APP_DATA_AVAILABLE_JBOX_IMAGE\0"
    "APP_DATA_AVAILABLE_USB1\0"
    "APP_DATA_AVAILABLE_USB1_VIDEO\0"
    "APP_DATA_AVAILABLE_USB1_AUDIO\0"
    "APP_DATA_AVAILABLE_USB1_IMAGE\0"
    "APP_DATA_AVAILABLE_USB2\0"
    "APP_DATA_AVAILABLE_USB2_VIDEO\0"
    "APP_DATA_AVAILABLE_USB2_AUDIO\0"
    "APP_DATA_AVAILABLE_USB2_IMAGE\0"
    "APP_DATA_AVAILABLE_DISC\0"
    "APP_DATA_AVAILABLE_DISC_DVD_VIDEO\0"
    "APP_DATA_AVAILABLE_DISC_VCD\0"
    "APP_DATA_AVAILABLE_DISC_DVD_AUDIO\0"
    "APP_DATA_AVAILABLE_DISC_MP3\0"
    "APP_DATA_AVAILABLE_DISC_CD\0"
    "APP_DATA_AVAILABLE_IPOD1\0"
    "APP_DATA_AVAILABLE_IPOD2\0"
    "APP_DATA_AVAILABLE_AUX\0APP_DATA_AVAILABLE_BT\0"
    "APP_DATA_AVAILABLE_BT_PANDORA\0"
    "APP_DATA_AVAILABLE_BT_AHA\0"
    "APP_DATA_AVAILABLE_IBOX_MODEM\0"
    "APP_DATA_AVAILABLE_PANDORA1\0"
    "APP_DATA_AVAILABLE_PANDORA2\0"
    "APP_DATA_AVAILABLE_AHA1\0APP_DATA_AVAILABLE_AHA2\0"
    "APP_DATA_AVAILABLE_MAXIMUM\0"
    "APP_DATA_ENABLED_MINIMUM\0APP_DATA_ENABLED_NAVI\0"
    "APP_DATA_ENABLED_MEDIA\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO\0"
    "APP_DATA_ENABLED_MEDIA_PHOTO\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO_JBOX\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO_USB1\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO_USB2\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO_DISC\0"
    "APP_DATA_ENABLED_MEDIA_VIDEO_AUX\0"
    "APP_DATA_ENABLED_MEDIA_PHOTO_JBOX\0"
    "APP_DATA_ENABLED_MEDIA_PHOTO_USB1\0"
    "APP_DATA_ENABLED_MEDIA_PHOTO_USB2\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_JBOX\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_USB1\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_USB2\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_DISC\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_IPOD1\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_IPOD2\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_AUX\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_BT\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_PANDORA\0"
    "APP_DATA_ENABLED_MEDIA_AUDIO_AHA\0"
    "APP_DATA_ENABLED_MEDIA_AUX\0"
    "APP_DATA_ENABLED_DRIVING_MODE\0"
    "APP_DATA_ENABLED_VR\0APP_DATA_ENABLED_HELP\0"
    "APP_DATA_ENABLED_PARKED\0"
    "APP_DATA_ENABLED_MAXIMUM\0APP_DATA_INT_MINIMUM\0"
    "APP_DATA_INT_MAXIMUM\0APP_DATA_MAX\0"
    "APP_ID_NAVI\0APP_ID_RADIO\0"
    "APP_ID_SIRIUS_XM_FROM_HOME\0APP_ID_DMB\0"
    "APP_ID_BT_PHONE\0APP_ID_AUX\0APP_ID_AUDIO_JBOX\0"
    "APP_ID_AUDIO_USB1\0APP_ID_AUDIO_USB2\0"
    "APP_ID_AUDIO_IPOD1\0APP_ID_AUDIO_IPOD2\0"
    "APP_ID_AUDIO_DISC\0APP_ID_AUDIO_BLUETOOTH\0"
    "APP_ID_PANDORA1\0APP_ID_PANDORA2\0"
    "APP_ID_AHA1\0APP_ID_AHA2\0APP_ID_BT_PANDORA\0"
    "APP_ID_BT_AHA\0APP_ID_VIDEO_JBOX\0"
    "APP_ID_VIDEO_USB1\0APP_ID_VIDEO_USB2\0"
    "APP_ID_VIDEO_DISC\0APP_ID_PHOTO_JBOX\0"
    "APP_ID_PHOTO_USB1\0APP_ID_PHOTO_USB2\0"
    "APP_ID_SETTINGS_SOUND\0APP_ID_SETTINGS_SCREEN\0"
    "APP_ID_SETTINGS_NAVI\0APP_ID_SETTINGS_BLUETOOTH\0"
    "APP_ID_SETTINGS_VR\0APP_ID_SETTINGS_CLOCK\0"
    "APP_ID_WIFI_SETTINGS\0"
    "APP_ID_SETTINGS_GENERAL_INITIALIZATION\0"
    "APP_ID_SETTINGS_GENERAL_VIDEO_MNGMNT\0"
    "APP_ID_SETTINGS_GENERAL_SYSTEM\0"
    "APP_ID_SETTINGS_GENERAL_BASIC\0"
    "APP_ID_DOWNLOAD_APP\0APP_ID_APP_STORE\0"
    "APP_ID_XM_DATA\0APP_ID_VIDEO_QUICK_GUIDE\0"
    "APP_ID_E_MANUAL\0APP_ID_BLUELINK_PHONE\0"
    "APP_ID_BLUELINK_ASSISTANT\0"
    "APP_ID_BLUELINK_SETTINGS\0APP_ID_DRIVING_INFO\0"
    "APP_ID_SEND_TO_CAR\0APP_ID_DAILY_ROUTE_GUIDANCE\0"
    "APP_ID_VEHICLE_DIAGNOSTICS\0"
    "APP_ID_SCHEDULED_DIAGNOSTICS\0"
    "APP_ID_MAINTENANCE\0APP_ID_BLUELINK_CENTER\0"
    "APP_ID_MODEM_PHONE_MAIN\0APP_ID_MODEM_DIAL\0"
    "APP_ID_MODEM_PHONEBOOK\0APP_ID_MODEM_CALL_HISTORY\0"
    "APP_ID_MAX\0APP_ID_INVALID\0IMG_NONE\0"
    "IMG_BG_MAIN\0IMG_ICON_APPLICATION\0"
    "IMG_ICON_AUX\0IMG_ICON_BLUELINK\0"
    "IMG_ICON_BLUELINK_ASSISTANT\0"
    "IMG_ICON_BLUELINK_CENTER\0"
    "IMG_ICON_BLUELINK_PHONE\0"
    "IMG_ICON_BLUELINK_SETTINGS\0"
    "IMG_ICON_BLUELINK_PHONE_DIAL\0"
    "IMG_ICON_BLUETOOTH\0IMG_ICON_BT\0"
    "IMG_ICON_BT_PANDORA\0IMG_ICON_BT_AHA\0"
    "IMG_ICON_BT_SET\0IMG_ICON_DISC\0"
    "IMG_ICON_DMB\0IMG_ICON_DRIVING_INFO\0"
    "IMG_ICON_E_MANUAL\0IMG_ICON_GENERAL\0"
    "IMG_ICON_INFO\0IMG_ICON_VIDEO_QUICK_GUIDE\0"
    "IMG_ICON_JBOX\0IMG_ICON_MEDIA\0IMG_ICON_NAVI\0"
    "IMG_ICON_NETWORK\0IMG_ICON_PANDORA\0"
    "IMG_ICON_RADIO\0IMG_ICON_SCREEN\0"
    "IMG_ICON_SEND_TO_CAR\0IMG_ICON_SETTING\0"
    "IMG_ICON_SOUND\0IMG_ICON_SYSTEM\0"
    "IMG_ICON_USB\0IMG_ICON_VEHICLE_DIAGNOSTICS\0"
    "IMG_ICON_VOIREC\0IMG_ICON_XM\0"
    "IMG_ICON_XM_DATA\0IMG_ICON_AUDIO_JUKEBOX\0"
    "IMG_ICON_AUDIO_USB\0IMG_ICON_PHOTO_USB\0"
    "IMG_ICON_PHOTO_JUKEBOX\0IMG_ICON_VIDEO_USB\0"
    "IMG_ICON_VIDEO_JUKEBOX\0IMG_TITLE_BG\0"
    "IMG_TITLE_BTN\0IMG_ICON_AHA\0IMG_ICON_IPOD\0"
    "IMG_ICON_CLOCK\0IMG_ICON_NAVI_SETTING\0"
    "IMG_ICON_MAIN_PHONE_180\0IMG_ICON_MAIN_PHONE_196\0"
    "IMG_ICON_MAIN_PHONE_226\0IMG_ICON_MAIN_PHONE_250\0"
    "IMG_ICON_MAIN_APPS_180\0"
    "IMG_ICON_MAIN_BLUELINK_180\0"
    "IMG_ICON_MAIN_SETTING_180\0"
    "IMG_ICON_MAIN_SETTING_196\0"
    "IMG_ICON_MAIN_SETTING_232\0"
    "IMG_ICON_MAIN_SETTING_238\0"
    "IMG_ICON_MAIN_MEDIA_180\0IMG_ICON_MAIN_MEDIA_196\0"
    "IMG_ICON_MAIN_MEDIA_226\0IMG_ICON_MAIN_MEDIA_234\0"
    "IMG_ICON_MAIN_MEDIA_246\0IMG_ICON_MAIN_MEDIA_250\0"
    "IMG_ICON_MAIN_MEDIA_270\0IMG_ICON_MAIN_DMB_234\0"
    "IMG_ICON_MAIN_DMB_246\0IMG_ICON_MAIN_RADIO_232\0"
    "IMG_ICON_MAIN_RADIO_234\0IMG_ICON_MAIN_RADIO_238\0"
    "IMG_ICON_MAIN_RADIO_246\0IMG_ICON_MAIN_RADIO_250\0"
    "IMG_ICON_MAIN_RADIO_270\0IMG_ICON_MAIN_NAVI_226\0"
    "IMG_ICON_MAIN_NAVI_232\0IMG_ICON_MAIN_NAVI_234\0"
    "IMG_ICON_MAIN_NAVI_246\0IMG_ICON_MAIN_XM_DATA_180\0"
    "IMG_ICON_MAIN_XM_DATA_226\0"
    "IMG_ICON_MAIN_XM_234\0IMG_ICON_MAIN_XM_246\0"
    "IMG_ICON_MAIN_XM_254\0IMG_MAX\0COLOR_BLACK\0"
    "COLOR_BRIGHT_GREY\0COLOR_SUB_TEXT_GREY\0"
    "COLOR_GREY\0COLOR_DIMMED_GREY\0"
    "COLOR_DISABLE_GREY\0COLOR_FOCUS_GREY\0"
    "COLOR_BUTTON_GREY\0COLOR_PROGRESS_BLUE\0"
    "COLOR_DIMMED_BLUE\0COLOR_128_191_255\0"
    "COLOR_112_112_112\0COLOR_41_41_41\0"
    "COLOR_MAX\0AV_TEXT_PIXEL_SIZE\0AV_TEXT_WIDTH\0"
    "AV_LINE1_COLOR\0AV_LINE2_COLOR\0AV_LINE_LO\0"
    "AV_LINE2_VCO\0AV_LINE1_VCO\0ICON_TEXT_WIDTH\0"
    "ICON_TEXT_SINGLE_VCM\0ICON_TEXT_DOUBLE_FIRST_VCM\0"
    "ICON_TEXT_DOUBLE_SECOND_VCM\0"
    "ICON_TEXT_PIXEL_SIZE\0ICON_TEXT_COLOR_NORMAL\0"
    "ICON_TEXT_COLOR_PRESSED\0"
    "ICON_TEXT_COLOR_DISABLED\0"
    "FOCUS_INDEX_ICONS_MENU\0FOCUS_INDEX_POPUP\0"
    "POPUP_INVALID\0POPUP_NO_MEDIA\0"
    "POPUP_NO_IMAGE\0POPUP_VR_NOT_SUPPORT\0"
    "POPUP_NO_SDCARD\0POPUP_SDCARD_NOT_SUPPORT_PREMIUM20\0"
    "POPUP_NO_IMAGE_IN_USB\0POPUP_NO_IMAGE_IN_JBOX\0"
    "POPUP_NO_MUSIC\0POPUP_NO_MUSIC_IN_USB\0"
    "POPUP_NO_MUSIC_IN_JBOX\0POPUP_NO_VIDEO\0"
    "POPUP_NO_VIDEO_IN_USB\0POPUP_NO_VIDEO_IN_JBOX\0"
    "POPUP_RESTRICTION\0POPUP_NO_PHONE_CONNECTED\0"
    "POPUP_NOT_USE_BLUELINK_PHONE\0"
    "POPUP_LOCAL_IGN\0POPUP_LOCAL_BLUELINK\0"
    "POPUP_LOCAL_DRS\0POPUP_DISABLE_BT_MUSIC\0"
    "POPUP_HELP_NOT_SUPPORT\0"
};

void HSDefP::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    Q_UNUSED(_o);
    Q_UNUSED(_id);
    Q_UNUSED(_c);
    Q_UNUSED(_a);
}

const QMetaObjectExtraData HSDefP::staticMetaObjectExtraData = {
    0,  qt_static_metacall 
};

const QMetaObject HSDefP::staticMetaObject = {
    { &QObject::staticMetaObject, qt_meta_stringdata_HSDefP,
      qt_meta_data_HSDefP, &staticMetaObjectExtraData }
};

#ifdef Q_NO_DATA_RELOCATION
const QMetaObject &HSDefP::getStaticMetaObject() { return staticMetaObject; }
#endif //Q_NO_DATA_RELOCATION

const QMetaObject *HSDefP::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->metaObject : &staticMetaObject;
}

void *HSDefP::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_HSDefP))
        return static_cast<void*>(const_cast< HSDefP*>(this));
    return QObject::qt_metacast(_clname);
}

int HSDefP::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = QObject::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    return _id;
}
QT_END_MOC_NAMESPACE
