/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a dab_adaptor -c DABAdaptor com.lge.car.micom.dab.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DAB_ADAPTOR_H_1364265337
#define DAB_ADAPTOR_H_1364265337

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.lge.car.micom.dab
 */
class DABAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.lge.car.micom.dab")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.lge.car.micom.dab\">\n"
"    <method name=\"LgeDBus_DABPICodeRequest\">\n"
"      <!-- 0x0126, 20130318(out:2bytes) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_DABTAStatus\">\n"
"      <!-- 0x0135, 20130326 -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <signal name=\"LgeDBus_EventDABPISensitivity\">\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"      <!-- 0x8328, 20130318(out:4bytes) -->\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DABAdaptor(QObject *parent);
    virtual ~DABAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void LgeDBus_DABPICodeRequest(const QByteArray &in0);
    void LgeDBus_DABTAStatus(uchar in0);
Q_SIGNALS: // SIGNALS
    void LgeDBus_EventDABPISensitivity(const QByteArray &in0);
};

#endif
