/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a sysinfo_adaptor -c SysInfoAdaptor com.lge.car.micom.sysinfo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SYSINFO_ADAPTOR_H_1392962812
#define SYSINFO_ADAPTOR_H_1392962812

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.lge.car.micom.sysinfo
 */
class SysInfoAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.lge.car.micom.sysinfo")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.lge.car.micom.sysinfo\">\n"
"    <method name=\"LgeDBus_AskSysBootType\">\n"
"      <!-- 0x201, Reponse:0x8201, v1.3_20111003(out:4bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskSysLastStatus\">\n"
"      <!-- 0x0202, Response:0x8202, v1.3_20111003(out:3bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SetSysOption\">\n"
"      <!-- 0x0193, v1.3_20111003(in:9bytes) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_EtcGUIMode\">\n"
"      <!-- 0x0190, (in:1bytes) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskSysVersion\">\n"
"      <!-- 0x0203, Response:0x8203, v1.3_20111003(out:16bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SetLanguageInfo\">\n"
"      <!-- 0x0197, v?.?_20120919 -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskLanguageInfoValue\">\n"
"      <!-- 0x0293, Response:0x8293, v?.?_20120919(out:1ytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskHDRadioVersion\">\n"
"      <!-- 0x0205, Response:0x8205, v?.?_20120312(out:40bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskMOST_INICVersion\">\n"
"      <!-- 0x0260, Response:0x8260, v?.?_20120423(out:12bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskSysOption\">\n"
"      <!-- 0x0204, Response:0x8204, v1.3_20111003(out:9bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_CPUAliveMsg\"/>\n"
"    <!-- 0x0198 -->\n"
"    <method name=\"LgeDBus_EmergencyConditionMsg\">\n"
"      <!-- 0x019C, (in:2bytes) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SettingValueStatusMsg\">\n"
"      <!-- 0x019D, (in:2bytes) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskSettingValueMsg\">\n"
"      <!-- 0x029D, (out:2bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SwVersionMsg\">\n"
"      <!-- 0x019E (in:3bytes)-->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_BTMACAddrStore\">\n"
"      <!-- 0x019F (in:4bytes)-->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskBTMACAddr\">\n"
"      <!-- 0x029F, Response:0x829F (out:4bytes)-->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskAMPVersion\">\n"
"      <!-- 0x0206, Response:0x8206 (out:5bytes)-->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <signal name=\"LgeDBus_EventCarIFStatus\">\n"
"      <!-- 0x8390, v1.3_20111003(out:2bytes) -->\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_EventDayNightStatus\">\n"
"      <!-- 0x8391, v1.3_20111003(out:1byte) -->\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_PopUpEvent\">\n"
"      <!-- 0x8392, (out:3byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_AudioMixCHCtrl\">\n"
"      <!-- 0x8112, (out:2byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_AudioMainCHCtrl\">\n"
"      <!-- 0x8110, (out:1byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_AudioLastMemory\">\n"
"      <!-- 0x8119, (out:2byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_AudioMuteCtrl\">\n"
"      <!-- 0x8116, (out:2byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    SysInfoAdaptor(QObject *parent);
    virtual ~SysInfoAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QByteArray LgeDBus_AskAMPVersion();
    QByteArray LgeDBus_AskBTMACAddr();
    QByteArray LgeDBus_AskHDRadioVersion();
    QByteArray LgeDBus_AskLanguageInfoValue();
    QByteArray LgeDBus_AskMOST_INICVersion();
    QByteArray LgeDBus_AskSettingValueMsg();
    QByteArray LgeDBus_AskSysBootType();
    QByteArray LgeDBus_AskSysLastStatus();
    QByteArray LgeDBus_AskSysOption();
    QByteArray LgeDBus_AskSysVersion();
    void LgeDBus_BTMACAddrStore(const QByteArray &in0);
    void LgeDBus_CPUAliveMsg();
    void LgeDBus_EmergencyConditionMsg(const QByteArray &in0);
    void LgeDBus_EtcGUIMode(uchar in0);
    void LgeDBus_SetLanguageInfo(uchar in0);
    void LgeDBus_SetSysOption(const QByteArray &in0);
    void LgeDBus_SettingValueStatusMsg(const QByteArray &in0);
    void LgeDBus_SwVersionMsg(const QByteArray &in0);
Q_SIGNALS: // SIGNALS
    void LgeDBus_AudioLastMemory(const QByteArray &in0);
    void LgeDBus_AudioMainCHCtrl(const QByteArray &in0);
    void LgeDBus_AudioMixCHCtrl(const QByteArray &in0);
    void LgeDBus_AudioMuteCtrl(const QByteArray &in0);
    void LgeDBus_EventCarIFStatus(uchar in0, uchar in1);
    void LgeDBus_EventDayNightStatus(uchar in0);
    void LgeDBus_PopUpEvent(const QByteArray &in0);
};

#endif
