/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a system_adaptor -c SystemAdaptor com.lge.car.micom.system.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SYSTEM_ADAPTOR_H_1388827131
#define SYSTEM_ADAPTOR_H_1388827131

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.lge.car.micom.system
 */
class SystemAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.lge.car.micom.system")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.lge.car.micom.system\">\n"
"    <signal name=\"LgeDBus_EventFrontSpecialKey\">\n"
"      <!-- 0x8375 from micom v0.8 avaiable(out:1byte)-->\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </signal>\n"
"    <signal name=\"LgeDBus_FactoryResetComplete\">\n"
"      <!-- 0x8360 (out:1byte)-->\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </signal>\n"
"    <method name=\"LgeDBus_SetFanControl\">\n"
"      <!-- 0x0163, v1.3_20111003(in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_ResetHWPeripheral\">\n"
"      <!-- 0x0164, (in:2byte) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SetPhoneMicControl\">\n"
"      <!-- 0x0165, v1.3_20111003(in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SetDiscIndicationLed\">\n"
"      <!-- 0x0168, v_1.4_20111010(in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_SetHwRTCSet\">\n"
"      <!-- 0x0166, v_1.3_20111003(in:7bytes) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AskRTCInfo\">\n"
"      <!-- 0x0291, Reponse:0x8291, v_1.3_20111003(out:7bytes) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_EEPROMWrite\">\n"
"      <!-- 0x0195, (in:variable) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_EEPROMRead\">\n"
"      <!-- 0x0295, Reponse:0x8295, (in, out:variable) -->\n"
"      <arg direction=\"in\" type=\"ay\"/>\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_AppBootComplete\">\n"
"      <!-- 0x0191, (in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_ETCFactorySetting\">\n"
"      <!-- 0x0192, (in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_MainImageUpgrade\">\n"
"      <!-- 0x0198, (in:1byte) -->\n"
"      <arg direction=\"in\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_WDTCountInfo\">\n"
"      <!-- 0x02A0, (out:4byte) -->\n"
"      <arg direction=\"out\" type=\"ay\"/>\n"
"    </method>\n"
"    <method name=\"LgeDBus_DATCInitialRequest\"/>\n"
"    <!-- 0x0180 20120207 -->\n"
"    <method name=\"LgeDBus_CarSetInitialRequest\"/>\n"
"    <!-- 0x0181 20120207 -->\n"
"    <method name=\"LgeDBus_CarInfoInitialRequest\"/>\n"
"    <!-- 0x0185 20120207 -->\n"
"    <method name=\"LgeDBus_PGSInitialRequest\"/>\n"
"    <!-- 0x0182 20120207 -->\n"
"    <method name=\"LgeDBus_AVMInitialRequest\"/>\n"
"    <!-- 0x0183 20120207 -->\n"
"    <method name=\"LgeDBus_WDTCountClear\"/>\n"
"    <!-- 0x01A0 20140104 -->\n"
"  </interface>\n"
        "")
public:
    SystemAdaptor(QObject *parent);
    virtual ~SystemAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void LgeDBus_AVMInitialRequest();
    void LgeDBus_AppBootComplete(uchar in0);
    QByteArray LgeDBus_AskRTCInfo();
    void LgeDBus_CarInfoInitialRequest();
    void LgeDBus_CarSetInitialRequest();
    void LgeDBus_DATCInitialRequest();
    QByteArray LgeDBus_EEPROMRead(const QByteArray &in0);
    void LgeDBus_EEPROMWrite(const QByteArray &in0);
    void LgeDBus_ETCFactorySetting(uchar in0);
    void LgeDBus_MainImageUpgrade(uchar in0);
    void LgeDBus_PGSInitialRequest();
    void LgeDBus_ResetHWPeripheral(const QByteArray &in0);
    void LgeDBus_SetDiscIndicationLed(uchar in0);
    void LgeDBus_SetFanControl(uchar in0);
    void LgeDBus_SetHwRTCSet(const QByteArray &in0);
    void LgeDBus_SetPhoneMicControl(uchar in0);
    void LgeDBus_WDTCountClear();
    QByteArray LgeDBus_WDTCountInfo();
Q_SIGNALS: // SIGNALS
    void LgeDBus_EventFrontSpecialKey(uchar in0);
    void LgeDBus_FactoryResetComplete(uchar in0);
};

#endif
