/*=!AUTO-GENERATED!============================================================
*
*     This code was generated by K2L MAG V2.3.4 at 2013-11-08.
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*     
*==!AUTO-GENERATED!============================================================*/

#include <stdint.h>
#include <K2LSystem.h>
#include <ACSStreams.h>
#include <K2LACSClient.h>
#include <K2LACSMOST.h>
#include <MOSTProtocolDefinitions.h>

#include "DHAVN_MOSTManager_LogFBlock.h"


acs::generated::fblock::Log::CMemoryCheck::CMemoryCheck(acs::generated::fblock::Log::CLog *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::Log::CMemoryCheck::~CMemoryCheck(void)
{
}
void acs::generated::fblock::Log::CMemoryCheck::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_memoryCheckFunction.SetListener( pListener );
}
bool acs::generated::fblock::Log::CMemoryCheck::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_memoryCheckFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassContainer& acs::generated::fblock::Log::CMemoryCheck::FunctionInstance(void)
{
	return m_pInstance->m_memoryCheckFunction;
}
bool acs::generated::fblock::Log::CMemoryCheck::MbmTxValue( uint16_t value )
{
    return m_pInstance->m_memoryCheckMbmTxParameter.Value( value );
}

uint16_t acs::generated::fblock::Log::CMemoryCheck::MbmTxValue() const
{
	return m_pInstance->m_memoryCheckMbmTxParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::Log::CMemoryCheck::MbmTxDataType()
{
    return m_pInstance->m_memoryCheckMbmTxParameter;
}
bool acs::generated::fblock::Log::CMemoryCheck::MbmRxValue( uint16_t value )
{
    return m_pInstance->m_memoryCheckMbmRxParameter.Value( value );
}

uint16_t acs::generated::fblock::Log::CMemoryCheck::MbmRxValue() const
{
	return m_pInstance->m_memoryCheckMbmRxParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::Log::CMemoryCheck::MbmRxDataType()
{
    return m_pInstance->m_memoryCheckMbmRxParameter;
}
bool acs::generated::fblock::Log::CMemoryCheck::MbmNumValue( uint16_t value )
{
    return m_pInstance->m_memoryCheckMbmNumParameter.Value( value );
}

uint16_t acs::generated::fblock::Log::CMemoryCheck::MbmNumValue() const
{
	return m_pInstance->m_memoryCheckMbmNumParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::Log::CMemoryCheck::MbmNumDataType()
{
    return m_pInstance->m_memoryCheckMbmNumParameter;
}
bool acs::generated::fblock::Log::CMemoryCheck::MbmMemoryValue( uint16_t value )
{
    return m_pInstance->m_memoryCheckMbmMemoryParameter.Value( value );
}

uint16_t acs::generated::fblock::Log::CMemoryCheck::MbmMemoryValue() const
{
	return m_pInstance->m_memoryCheckMbmMemoryParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::Log::CMemoryCheck::MbmMemoryDataType()
{
    return m_pInstance->m_memoryCheckMbmMemoryParameter;
}
bool acs::generated::fblock::Log::CMemoryCheck::MbmFragValue( uint16_t value )
{
    return m_pInstance->m_memoryCheckMbmFragParameter.Value( value );
}

uint16_t acs::generated::fblock::Log::CMemoryCheck::MbmFragValue() const
{
	return m_pInstance->m_memoryCheckMbmFragParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::Log::CMemoryCheck::MbmFragDataType()
{
    return m_pInstance->m_memoryCheckMbmFragParameter;
}
bool acs::generated::fblock::Log::CMemoryCheck::MemoryValue( uint8_t * value, uint8_t length )
{
    return m_pInstance->m_memoryCheckMemoryParameter.Stream( value, length );
}

const uint8_t * acs::generated::fblock::Log::CMemoryCheck::MemoryValue() const
{
	return m_pInstance->m_memoryCheckMemoryParameter.Stream();
}
::k2l::acs::protocols::most::CMOSTShortList& acs::generated::fblock::Log::CMemoryCheck::MemoryDataType()
{
    return m_pInstance->m_memoryCheckMemoryParameter;
}
uint8_t acs::generated::fblock::Log::CMemoryCheck::MemoryStreamLength() const
{
	return m_pInstance->m_memoryCheckMemoryParameter.StreamLength();
}
bool acs::generated::fblock::Log::CMemoryCheck::MemoryLoadNext()
{
    return m_pInstance->m_memoryCheckMemoryParameter.LoadNext();
}
bool acs::generated::fblock::Log::CMemoryCheck::MemorySaveNext()
{
    return m_pInstance->m_memoryCheckMemoryParameter.SaveNext();
}



acs::generated::fblock::Log::CLog::CLog(k2l::acs::protocols::most::InstanceID_t instanceID):
	::k2l::acs::protocols::most::CFunctionBlockBase(FBlockID, instanceID)
{
}

acs::generated::fblock::Log::CLog::CLog(k2l::acs::protocols::most::FBlockID_t fblockID, k2l::acs::protocols::most::InstanceID_t instanceID):
	::k2l::acs::protocols::most::CFunctionBlockBase(fblockID, instanceID)
{
}

acs::generated::fblock::Log::CLog::~CLog(void)
{
}

/*virtual*/
bool
acs::generated::fblock::Log::CLog::InitializeMOSTElement()
{
	k2l::acs::protocols::most::CMOSTDataType *elements[5];
m_memoryCheckFunction.FunctionID( 0xF01 );
m_memoryCheckFunction.Notification( false );
m_memoryCheckFunction.AutomaticNotification( false );
m_memoryCheckFunction.SupportedOperations( 0x1 );
elements[0] = &m_memoryCheckMbmTxParameter;
elements[1] = &m_memoryCheckMbmRxParameter;
elements[2] = &m_memoryCheckMbmNumParameter;
elements[3] = &m_memoryCheckMbmMemoryParameter;
elements[4] = &m_memoryCheckMbmFragParameter;
m_memoryCheckMemoryRecordFixParameter.SetMembers( 5, elements );
m_memoryCheckMemoryParameter.SetRecordFix( m_memoryCheckMemoryRecordFixParameter );
m_memoryCheckMemoryRecordIteratorParameter.SetMembers( 0, elements );
m_memoryCheckMemoryParameter.SetRecordIterator( m_memoryCheckMemoryRecordIteratorParameter );
m_memoryCheckFunction.SetValueType( &m_memoryCheckMemoryParameter );
AddFunction( &m_memoryCheckFunction );
AddFunction( &m_notificationCheckFunction );
AddFunction( &m_notificationFunction );
AddFunction( &m_fktIDsFunction );
NotificationService( &m_notificationFunction );
m_notificationFunction.Update();
m_fktIDsFunction.Update();
return true;
}


/*=============================================================================
 * END OF FILE
 *=============================================================================*/
