/*=!AUTO-GENERATED!============================================================
*
*     This code was generated by K2L MAG V2.3.4 at 2013-04-22.
*
*     Changes to this file may cause incorrect behavior and will be lost if
*     the code is regenerated.
*     
*==!AUTO-GENERATED!============================================================*/

/**
 * HMC DH Fcat v1.23.1
 **/

#include <stdint.h>
#include <K2LSystem.h>
#include <ACSStreams.h>
#include <K2LACSClient.h>
#include <K2LACSMOST.h>
#include <MOSTProtocolDefinitions.h>

#include "DHAVN_MOSTManager_DMBTunerFBlock.h"


acs::generated::fblock::DMBTuner::CVersion::CVersion(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CVersion::~CVersion(void)
{
}
void acs::generated::fblock::DMBTuner::CVersion::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_versionFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CVersion::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_versionFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassUnclassifiedProperty& acs::generated::fblock::DMBTuner::CVersion::FunctionInstance(void)
{
	return m_pInstance->m_versionFunction;
}
bool acs::generated::fblock::DMBTuner::CVersion::MajorValue( uint8_t value )
{
    return m_pInstance->m_versionMajorParameter.Value( value );
}

uint8_t acs::generated::fblock::DMBTuner::CVersion::MajorValue() const
{
	return m_pInstance->m_versionMajorParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedByte& acs::generated::fblock::DMBTuner::CVersion::MajorDataType()
{
    return m_pInstance->m_versionMajorParameter;
}
bool acs::generated::fblock::DMBTuner::CVersion::MinorValue( uint8_t value )
{
    return m_pInstance->m_versionMinorParameter.Value( value );
}

uint8_t acs::generated::fblock::DMBTuner::CVersion::MinorValue() const
{
	return m_pInstance->m_versionMinorParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedByte& acs::generated::fblock::DMBTuner::CVersion::MinorDataType()
{
    return m_pInstance->m_versionMinorParameter;
}
bool acs::generated::fblock::DMBTuner::CVersion::BuildValue( uint8_t value )
{
    return m_pInstance->m_versionBuildParameter.Value( value );
}

uint8_t acs::generated::fblock::DMBTuner::CVersion::BuildValue() const
{
	return m_pInstance->m_versionBuildParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedByte& acs::generated::fblock::DMBTuner::CVersion::BuildDataType()
{
    return m_pInstance->m_versionBuildParameter;
}
bool acs::generated::fblock::DMBTuner::CVersion::UpdateShadows()
{
    return m_pInstance->m_versionFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CVersion::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_versionFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CVersion::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_versionFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CFBlockInfo::CFBlockInfo(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CFBlockInfo::~CFBlockInfo(void)
{
}
void acs::generated::fblock::DMBTuner::CFBlockInfo::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_fBlockInfoFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_fBlockInfoFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassUnclassifiedProperty& acs::generated::fblock::DMBTuner::CFBlockInfo::FunctionInstance(void)
{
	return m_pInstance->m_fBlockInfoFunction;
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::IDValue( uint16_t value )
{
    return m_pInstance->m_fBlockInfoIDParameter.Value( value );
}

uint16_t acs::generated::fblock::DMBTuner::CFBlockInfo::IDValue() const
{
	return m_pInstance->m_fBlockInfoIDParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::DMBTuner::CFBlockInfo::IDDataType()
{
    return m_pInstance->m_fBlockInfoIDParameter;
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FunctionMaturityValue( acs::generated::fblock::DMBTuner::CFBlockInfo::TFunctionMaturity value )
{
    return m_pInstance->m_fBlockInfoFunctionMaturityParameter.Value( value );
}

acs::generated::fblock::DMBTuner::CFBlockInfo::TFunctionMaturity acs::generated::fblock::DMBTuner::CFBlockInfo::FunctionMaturityValue() const
{
	return (acs::generated::fblock::DMBTuner::CFBlockInfo::TFunctionMaturity)m_pInstance->m_fBlockInfoFunctionMaturityParameter.Value();
}
::k2l::acs::protocols::most::CMOSTEnum& acs::generated::fblock::DMBTuner::CFBlockInfo::FunctionMaturityDataType()
{
    return m_pInstance->m_fBlockInfoFunctionMaturityParameter;
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoFBlockNameParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameValue() const
{
	return m_pInstance->m_fBlockInfoFBlockNameParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameDataType()
{
    return m_pInstance->m_fBlockInfoFBlockNameParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameLength() const
{
	return m_pInstance->m_fBlockInfoFBlockNameParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoFBlockNameParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoFBlockNameParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockNameString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoFBlockNameParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoSupplierVersionParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionValue() const
{
	return m_pInstance->m_fBlockInfoSupplierVersionParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionDataType()
{
    return m_pInstance->m_fBlockInfoSupplierVersionParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionLength() const
{
	return m_pInstance->m_fBlockInfoSupplierVersionParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoSupplierVersionParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoSupplierVersionParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SupplierVersionString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoSupplierVersionParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoFBlockVersionParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionValue() const
{
	return m_pInstance->m_fBlockInfoFBlockVersionParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionDataType()
{
    return m_pInstance->m_fBlockInfoFBlockVersionParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionLength() const
{
	return m_pInstance->m_fBlockInfoFBlockVersionParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoFBlockVersionParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoFBlockVersionParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockVersionString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoFBlockVersionParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoMOSTVersionParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionValue() const
{
	return m_pInstance->m_fBlockInfoMOSTVersionParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionDataType()
{
    return m_pInstance->m_fBlockInfoMOSTVersionParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionLength() const
{
	return m_pInstance->m_fBlockInfoMOSTVersionParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoMOSTVersionParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoMOSTVersionParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::MOSTVersionString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoMOSTVersionParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoSystemIntegratorParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorValue() const
{
	return m_pInstance->m_fBlockInfoSystemIntegratorParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorDataType()
{
    return m_pInstance->m_fBlockInfoSystemIntegratorParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorLength() const
{
	return m_pInstance->m_fBlockInfoSystemIntegratorParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoSystemIntegratorParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoSystemIntegratorParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::SystemIntegratorString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoSystemIntegratorParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoFBlockTypeParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeValue() const
{
	return m_pInstance->m_fBlockInfoFBlockTypeParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeDataType()
{
    return m_pInstance->m_fBlockInfoFBlockTypeParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeLength() const
{
	return m_pInstance->m_fBlockInfoFBlockTypeParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_fBlockInfoFBlockTypeParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_fBlockInfoFBlockTypeParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::FBlockTypeString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_fBlockInfoFBlockTypeParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_fBlockInfoDescriptionParameter.Stream( value, length );
}

const uint8_t * acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionValue() const
{
	return m_pInstance->m_fBlockInfoDescriptionParameter.Stream();
}
::k2l::acs::protocols::most::CMOSTCaseStream& acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionDataType()
{
    return m_pInstance->m_fBlockInfoDescriptionParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionStreamLength() const
{
	return m_pInstance->m_fBlockInfoDescriptionParameter.StreamLength();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionLoadNext()
{
    return m_pInstance->m_fBlockInfoDescriptionParameter.LoadNext();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::DescriptionSaveNext()
{
    return m_pInstance->m_fBlockInfoDescriptionParameter.SaveNext();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::UpdateShadows()
{
    return m_pInstance->m_fBlockInfoFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_fBlockInfoFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CFBlockInfo::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_fBlockInfoFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CSignalQuality::CSignalQuality(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CSignalQuality::~CSignalQuality(void)
{
}
void acs::generated::fblock::DMBTuner::CSignalQuality::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_signalQualityFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CSignalQuality::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_signalQualityFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassSequenceProperty& acs::generated::fblock::DMBTuner::CSignalQuality::FunctionInstance(void)
{
	return m_pInstance->m_signalQualityFunction;
}
bool acs::generated::fblock::DMBTuner::CSignalQuality::DMBSignalQualityValue( uint8_t value )
{
    return m_pInstance->m_signalQualityDMBSignalQualityParameter.Value( value );
}

uint8_t acs::generated::fblock::DMBTuner::CSignalQuality::DMBSignalQualityValue() const
{
	return m_pInstance->m_signalQualityDMBSignalQualityParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedByte& acs::generated::fblock::DMBTuner::CSignalQuality::DMBSignalQualityDataType()
{
    return m_pInstance->m_signalQualityDMBSignalQualityParameter;
}
bool acs::generated::fblock::DMBTuner::CSignalQuality::UpdateShadows()
{
    return m_pInstance->m_signalQualityFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CSignalQuality::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_signalQualityFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CSignalQuality::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_signalQualityFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CTPEGStatus::CTPEGStatus(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CTPEGStatus::~CTPEGStatus(void)
{
}
void acs::generated::fblock::DMBTuner::CTPEGStatus::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_tPEGStatusFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CTPEGStatus::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_tPEGStatusFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassSequenceProperty& acs::generated::fblock::DMBTuner::CTPEGStatus::FunctionInstance(void)
{
	return m_pInstance->m_tPEGStatusFunction;
}
bool acs::generated::fblock::DMBTuner::CTPEGStatus::TPEGStatusValue( acs::generated::fblock::DMBTuner::CTPEGStatus::TTPEGStatus value )
{
    return m_pInstance->m_tPEGStatusParameter.Value( value );
}

acs::generated::fblock::DMBTuner::CTPEGStatus::TTPEGStatus acs::generated::fblock::DMBTuner::CTPEGStatus::TPEGStatusValue() const
{
	return (acs::generated::fblock::DMBTuner::CTPEGStatus::TTPEGStatus)m_pInstance->m_tPEGStatusParameter.Value();
}
::k2l::acs::protocols::most::CMOSTEnum& acs::generated::fblock::DMBTuner::CTPEGStatus::TPEGStatusDataType()
{
    return m_pInstance->m_tPEGStatusParameter;
}
bool acs::generated::fblock::DMBTuner::CTPEGStatus::UpdateShadows()
{
    return m_pInstance->m_tPEGStatusFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CTPEGStatus::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_tPEGStatusFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CTPEGStatus::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_tPEGStatusFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CTPEGInfo::CTPEGInfo(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CTPEGInfo::~CTPEGInfo(void)
{
}
void acs::generated::fblock::DMBTuner::CTPEGInfo::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_tPEGInfoFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_tPEGInfoFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassSequenceProperty& acs::generated::fblock::DMBTuner::CTPEGInfo::FunctionInstance(void)
{
	return m_pInstance->m_tPEGInfoFunction;
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_tPEGInfoRecevieDateParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateValue() const
{
	return m_pInstance->m_tPEGInfoRecevieDateParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateDataType()
{
    return m_pInstance->m_tPEGInfoRecevieDateParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateLength() const
{
	return m_pInstance->m_tPEGInfoRecevieDateParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_tPEGInfoRecevieDateParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_tPEGInfoRecevieDateParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieDateString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_tPEGInfoRecevieDateParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_tPEGInfoRecevieTimeParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeValue() const
{
	return m_pInstance->m_tPEGInfoRecevieTimeParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeDataType()
{
    return m_pInstance->m_tPEGInfoRecevieTimeParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeLength() const
{
	return m_pInstance->m_tPEGInfoRecevieTimeParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_tPEGInfoRecevieTimeParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_tPEGInfoRecevieTimeParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTimeString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_tPEGInfoRecevieTimeParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_tPEGInfoRecevieTextParameter.MOSTString( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextValue() const
{
	return m_pInstance->m_tPEGInfoRecevieTextParameter.MOSTStringContent();
}
::k2l::acs::protocols::most::CMOSTString& acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextDataType()
{
    return m_pInstance->m_tPEGInfoRecevieTextParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextLength() const
{
	return m_pInstance->m_tPEGInfoRecevieTextParameter.MOSTStringLength();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextAddEncoding(uint8_t mostStringIdentifier, const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding )            
{
    return m_pInstance->m_tPEGInfoRecevieTextParameter.AddEncoding( mostStringIdentifier, pStringEncoding );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextString(const k2l::acs::protocols::most::string::IStringEncoding* pStringEncoding, const uint8_t* pStringContent, uint32_t stringLengthBytes )
{
    return m_pInstance->m_tPEGInfoRecevieTextParameter.String( pStringEncoding, pStringContent, stringLengthBytes );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::RecevieTextString(const k2l::acs::protocols::most::string::IStringEncoding** ppStringEncoding, uint8_t** ppString, uint32_t* pStringLength )
{
    return m_pInstance->m_tPEGInfoRecevieTextParameter.String( ppStringEncoding, ppString, pStringLength );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_tPEGInfoParameter.Stream( value, length );
}

const uint8_t * acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoValue() const
{
	return m_pInstance->m_tPEGInfoParameter.Stream();
}
::k2l::acs::protocols::most::CMOSTList& acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoDataType()
{
    return m_pInstance->m_tPEGInfoParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoStreamLength() const
{
	return m_pInstance->m_tPEGInfoParameter.StreamLength();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoLoadNext()
{
    return m_pInstance->m_tPEGInfoParameter.LoadNext();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::TPEGInfoSaveNext()
{
    return m_pInstance->m_tPEGInfoParameter.SaveNext();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::UpdateShadows()
{
    return m_pInstance->m_tPEGInfoFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_tPEGInfoFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CTPEGInfo::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_tPEGInfoFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CDMBStatus::CDMBStatus(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CDMBStatus::~CDMBStatus(void)
{
}
void acs::generated::fblock::DMBTuner::CDMBStatus::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_dMBStatusFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_dMBStatusFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassSequenceProperty& acs::generated::fblock::DMBTuner::CDMBStatus::FunctionInstance(void)
{
	return m_pInstance->m_dMBStatusFunction;
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::DMBStatusValue( acs::generated::fblock::DMBTuner::CDMBStatus::TDMBStatus value )
{
    return m_pInstance->m_dMBStatusParameter.Value( value );
}

acs::generated::fblock::DMBTuner::CDMBStatus::TDMBStatus acs::generated::fblock::DMBTuner::CDMBStatus::DMBStatusValue() const
{
	return (acs::generated::fblock::DMBTuner::CDMBStatus::TDMBStatus)m_pInstance->m_dMBStatusParameter.Value();
}
::k2l::acs::protocols::most::CMOSTEnum& acs::generated::fblock::DMBTuner::CDMBStatus::DMBStatusDataType()
{
    return m_pInstance->m_dMBStatusParameter;
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::CurrentBrowserListLengthValue( uint8_t value )
{
    return m_pInstance->m_dMBStatusCurrentBrowserListLengthParameter.Value( value );
}

uint8_t acs::generated::fblock::DMBTuner::CDMBStatus::CurrentBrowserListLengthValue() const
{
	return m_pInstance->m_dMBStatusCurrentBrowserListLengthParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedByte& acs::generated::fblock::DMBTuner::CDMBStatus::CurrentBrowserListLengthDataType()
{
    return m_pInstance->m_dMBStatusCurrentBrowserListLengthParameter;
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::UpdateShadows()
{
    return m_pInstance->m_dMBStatusFunction.UpdateShadows();
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint32_t payloadLength, const uint8_t * payload )
{
    return m_pInstance->m_dMBStatusFunction.Error( targetDevice, payloadLength, payload );
}
bool acs::generated::fblock::DMBTuner::CDMBStatus::Error( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_dMBStatusFunction.Error( targetDevice, errorCode, errorInfoLength, pErrorInfo );
}



acs::generated::fblock::DMBTuner::CTPEGDataRequest::CTPEGDataRequest(acs::generated::fblock::DMBTuner::CDMBTuner *pInstance) : m_pInstance(pInstance)
{
}
acs::generated::fblock::DMBTuner::CTPEGDataRequest::~CTPEGDataRequest(void)
{
}
void acs::generated::fblock::DMBTuner::CTPEGDataRequest::SetListener(::k2l::acs::protocols::most::IACSMOSTEventListener * pListener)
{
	m_pInstance->m_tPEGDataRequestFunction.SetListener( pListener );
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::RemoveListener(::k2l::acs::protocols::most::IACSMOSTEventListener *pListener)
{
	return m_pInstance->m_tPEGDataRequestFunction.RemoveListener( pListener );
}
::k2l::acs::protocols::most::CMOSTFunctionClassSequenceMethod& acs::generated::fblock::DMBTuner::CTPEGDataRequest::FunctionInstance(void)
{
	return m_pInstance->m_tPEGDataRequestFunction;
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::SenderHandleValue( uint16_t value )
{
    return m_pInstance->m_tPEGDataRequestSenderHandleParameter.Value( value );
}

uint16_t acs::generated::fblock::DMBTuner::CTPEGDataRequest::SenderHandleValue() const
{
	return m_pInstance->m_tPEGDataRequestSenderHandleParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::DMBTuner::CTPEGDataRequest::SenderHandleDataType()
{
    return m_pInstance->m_tPEGDataRequestSenderHandleParameter;
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockCounterValue( uint32_t value )
{
    return m_pInstance->m_tPEGDataRequestBlockCounterParameter.Value( value );
}

uint32_t acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockCounterValue() const
{
	return m_pInstance->m_tPEGDataRequestBlockCounterParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedLong& acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockCounterDataType()
{
    return m_pInstance->m_tPEGDataRequestBlockCounterParameter;
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::ParseStartResultAck( uint32_t payloadLength, const uint8_t * payload )
						{
    ::k2l::acs::protocols::most::CMOSTDataType* parameters[2] = { &(m_pInstance->m_tPEGDataRequestSenderHandleParameter), 
&(m_pInstance->m_tPEGDataRequestBlockCounterParameter) };
    return m_pInstance->m_tPEGDataRequestFunction.ParsePayload( payloadLength, payload, 2, parameters );
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockTypeValue( acs::generated::fblock::DMBTuner::CTPEGDataRequest::TBlockType value )
{
    return m_pInstance->m_tPEGDataRequestBlockTypeParameter.Value( value );
}

acs::generated::fblock::DMBTuner::CTPEGDataRequest::TBlockType acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockTypeValue() const
{
	return (acs::generated::fblock::DMBTuner::CTPEGDataRequest::TBlockType)m_pInstance->m_tPEGDataRequestBlockTypeParameter.Value();
}
::k2l::acs::protocols::most::CMOSTEnum& acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockTypeDataType()
{
    return m_pInstance->m_tPEGDataRequestBlockTypeParameter;
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockSizeValue( uint16_t value )
{
    return m_pInstance->m_tPEGDataRequestBlockSizeParameter.Value( value );
}

uint16_t acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockSizeValue() const
{
	return m_pInstance->m_tPEGDataRequestBlockSizeParameter.Value();
}
::k2l::acs::protocols::most::CMOSTUnsignedWord& acs::generated::fblock::DMBTuner::CTPEGDataRequest::BlockSizeDataType()
{
    return m_pInstance->m_tPEGDataRequestBlockSizeParameter;
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::TPEGDataValue( uint8_t * value, uint32_t length )
{
    return m_pInstance->m_tPEGDataRequestTPEGDataParameter.Stream( value, length );
}

uint8_t * acs::generated::fblock::DMBTuner::CTPEGDataRequest::TPEGDataValue() const
{
	return m_pInstance->m_tPEGDataRequestTPEGDataParameter.Stream();
}
::k2l::acs::protocols::most::CMOSTStream& acs::generated::fblock::DMBTuner::CTPEGDataRequest::TPEGDataDataType()
{
    return m_pInstance->m_tPEGDataRequestTPEGDataParameter;
}
uint32_t acs::generated::fblock::DMBTuner::CTPEGDataRequest::TPEGDataStreamLength() const
{
	return m_pInstance->m_tPEGDataRequestTPEGDataParameter.StreamLength();
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::ResultAck( ::k2l::acs::protocols::most::DeviceID_t targetDevice )
{
    ::k2l::acs::protocols::most::CMOSTDataType* parameters[5] = { &(m_pInstance->m_tPEGDataRequestSenderHandleParameter), 
&(m_pInstance->m_tPEGDataRequestBlockTypeParameter), 
&(m_pInstance->m_tPEGDataRequestBlockCounterParameter), 
&(m_pInstance->m_tPEGDataRequestBlockSizeParameter), 
&(m_pInstance->m_tPEGDataRequestTPEGDataParameter) };
    return m_pInstance->m_tPEGDataRequestFunction.ResultAck( targetDevice, 5, parameters );
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::ProcessingAck( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint16_t senderHandle )
{
    return m_pInstance->m_tPEGDataRequestFunction.ProcessingAck( targetDevice, senderHandle );
}
void acs::generated::fblock::DMBTuner::CTPEGDataRequest::SetHandler( ::k2l::acs::protocols::most::IFunctionBlockMethodHandler *pHandler )
{
    m_pInstance->m_tPEGDataRequestFunction.SetHandler( pHandler );
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::ParseSenderHandle( uint32_t payloadLength, const uint8_t *payload, uint16_t *pSenderHandle )
{
    return m_pInstance->m_tPEGDataRequestFunction.ParseSenderHandle( payloadLength, payload, pSenderHandle );
}
bool acs::generated::fblock::DMBTuner::CTPEGDataRequest::ErrorAck( ::k2l::acs::protocols::most::DeviceID_t targetDevice, uint16_t senderHandle, uint8_t errorCode, uint32_t errorInfoLength, const uint8_t *pErrorInfo )
{
    return m_pInstance->m_tPEGDataRequestFunction.ErrorAck( targetDevice, senderHandle, errorCode, errorInfoLength, pErrorInfo );
}


const uint8_t acs::generated::fblock::DMBTuner::CDMBTuner::m_fBlockInfoFunctionMaturityParameterSpecValues[] = { 0, 1, 2, 3, 17, 18 };
const uint8_t acs::generated::fblock::DMBTuner::CDMBTuner::m_tPEGStatusParameterSpecValues[] = { 0, 1, 2 };
const uint8_t acs::generated::fblock::DMBTuner::CDMBTuner::m_dMBStatusParameterSpecValues[] = { 0, 1 };
const uint8_t acs::generated::fblock::DMBTuner::CDMBTuner::m_tPEGDataRequestBlockTypeParameterSpecValues[] = { 1, 2, 3 };


acs::generated::fblock::DMBTuner::CDMBTuner::CDMBTuner(k2l::acs::protocols::most::InstanceID_t instanceID):
	::k2l::acs::protocols::most::CFunctionBlockBase(FBlockID, instanceID)
{
}

acs::generated::fblock::DMBTuner::CDMBTuner::CDMBTuner(k2l::acs::protocols::most::FBlockID_t fblockID, k2l::acs::protocols::most::InstanceID_t instanceID):
	::k2l::acs::protocols::most::CFunctionBlockBase(fblockID, instanceID)
{
}

acs::generated::fblock::DMBTuner::CDMBTuner::~CDMBTuner(void)
{
}

/*virtual*/
bool
acs::generated::fblock::DMBTuner::CDMBTuner::InitializeMOSTElement()
{
	k2l::acs::protocols::most::CMOSTDataType *elements[8];
m_versionFunction.FunctionID( 0x10 );
m_versionFunction.Notification( false );
m_versionFunction.AutomaticNotification( true );
m_versionFunction.SupportedOperations( 0x9002 );
elements[0] = &m_versionMajorParameter;
elements[1] = &m_versionMinorParameter;
elements[2] = &m_versionBuildParameter;
m_versionFunction.SetDataItems(12, 3, elements);
AddFunction( &m_versionFunction );
m_fBlockInfoFunction.FunctionID( 0x11 );
m_fBlockInfoFunction.Notification( false );
m_fBlockInfoFunction.AutomaticNotification( true );
m_fBlockInfoFunction.SupportedOperations( 0x9002 );
m_fBlockInfoFunctionMaturityParameterSpec.Values( 6, m_fBlockInfoFunctionMaturityParameterSpecValues );
m_fBlockInfoFBlockNameParameterSpec.MaxCharacters( 0 );
m_fBlockInfoSupplierVersionParameterSpec.MaxCharacters( 0 );
m_fBlockInfoFBlockVersionParameterSpec.MaxCharacters( 0 );
m_fBlockInfoMOSTVersionParameterSpec.MaxCharacters( 0 );
m_fBlockInfoSystemIntegratorParameterSpec.MaxCharacters( 0 );
m_fBlockInfoFBlockTypeParameterSpec.MaxCharacters( 0 );
m_fBlockInfoFunctionMaturityParameter.SetValidator( &m_fBlockInfoFunctionMaturityParameterSpec );
m_fBlockInfoFunctionMaturityParameter.Value( m_fBlockInfoFunctionMaturityParameterSpecValues[0] );
m_fBlockInfoFBlockNameParameter.SetValidator( &m_fBlockInfoFBlockNameParameterSpec );
m_fBlockInfoSupplierVersionParameter.SetValidator( &m_fBlockInfoSupplierVersionParameterSpec );
m_fBlockInfoFBlockVersionParameter.SetValidator( &m_fBlockInfoFBlockVersionParameterSpec );
m_fBlockInfoMOSTVersionParameter.SetValidator( &m_fBlockInfoMOSTVersionParameterSpec );
m_fBlockInfoSystemIntegratorParameter.SetValidator( &m_fBlockInfoSystemIntegratorParameterSpec );
m_fBlockInfoFBlockTypeParameter.SetValidator( &m_fBlockInfoFBlockTypeParameterSpec );
elements[0] = &m_fBlockInfoFunctionMaturityParameter;
m_fBlockInfoDescription0RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription0Parameter.SetRecordFix( m_fBlockInfoDescription0RecordFixParameter );
m_fBlockInfoDescription0RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription0Parameter.SetRecordIterator( m_fBlockInfoDescription0RecordIteratorParameter );
elements[0] = &m_fBlockInfoFBlockNameParameter;
elements[1] = &m_fBlockInfoSupplierVersionParameter;
elements[2] = &m_fBlockInfoFBlockVersionParameter;
elements[3] = &m_fBlockInfoMOSTVersionParameter;
elements[4] = &m_fBlockInfoSystemIntegratorParameter;
elements[5] = &m_fBlockInfoFBlockTypeParameter;
m_fBlockInfoDescription61440RecordFixParameter.SetMembers( 6, elements );
m_fBlockInfoDescription61440Parameter.SetRecordFix( m_fBlockInfoDescription61440RecordFixParameter );
m_fBlockInfoDescription61440RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61440Parameter.SetRecordIterator( m_fBlockInfoDescription61440RecordIteratorParameter );
elements[0] = &m_fBlockInfoFBlockNameParameter;
m_fBlockInfoDescription61441RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61441Parameter.SetRecordFix( m_fBlockInfoDescription61441RecordFixParameter );
m_fBlockInfoDescription61441RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61441Parameter.SetRecordIterator( m_fBlockInfoDescription61441RecordIteratorParameter );
elements[0] = &m_fBlockInfoSupplierVersionParameter;
m_fBlockInfoDescription61442RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61442Parameter.SetRecordFix( m_fBlockInfoDescription61442RecordFixParameter );
m_fBlockInfoDescription61442RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61442Parameter.SetRecordIterator( m_fBlockInfoDescription61442RecordIteratorParameter );
elements[0] = &m_fBlockInfoFBlockVersionParameter;
m_fBlockInfoDescription61443RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61443Parameter.SetRecordFix( m_fBlockInfoDescription61443RecordFixParameter );
m_fBlockInfoDescription61443RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61443Parameter.SetRecordIterator( m_fBlockInfoDescription61443RecordIteratorParameter );
elements[0] = &m_fBlockInfoMOSTVersionParameter;
m_fBlockInfoDescription61444RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61444Parameter.SetRecordFix( m_fBlockInfoDescription61444RecordFixParameter );
m_fBlockInfoDescription61444RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61444Parameter.SetRecordIterator( m_fBlockInfoDescription61444RecordIteratorParameter );
elements[0] = &m_fBlockInfoSystemIntegratorParameter;
m_fBlockInfoDescription61445RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61445Parameter.SetRecordFix( m_fBlockInfoDescription61445RecordFixParameter );
m_fBlockInfoDescription61445RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61445Parameter.SetRecordIterator( m_fBlockInfoDescription61445RecordIteratorParameter );
elements[0] = &m_fBlockInfoFBlockTypeParameter;
m_fBlockInfoDescription61446RecordFixParameter.SetMembers( 1, elements );
m_fBlockInfoDescription61446Parameter.SetRecordFix( m_fBlockInfoDescription61446RecordFixParameter );
m_fBlockInfoDescription61446RecordIteratorParameter.SetMembers( 0, elements );
m_fBlockInfoDescription61446Parameter.SetRecordIterator( m_fBlockInfoDescription61446RecordIteratorParameter );
{
    uint32_t minValues[] = {0, 61440, 61441, 61442, 61443, 61444, 61445, 61446};
    uint32_t maxValues[] = {4095, 61440, 61441, 61442, 61443, 61444, 61445, 61446};
    k2l::acs::protocols::most::CMOSTList* streamCases[] = { &m_fBlockInfoDescription0Parameter,  &m_fBlockInfoDescription61440Parameter,  &m_fBlockInfoDescription61441Parameter,  &m_fBlockInfoDescription61442Parameter,  &m_fBlockInfoDescription61443Parameter,  &m_fBlockInfoDescription61444Parameter,  &m_fBlockInfoDescription61445Parameter,  &m_fBlockInfoDescription61446Parameter};
    m_fBlockInfoDescriptionParameter.SetStreamCases( 8, minValues, maxValues, streamCases );
}
m_fBlockInfoDescriptionParameter.SetSelector( m_fBlockInfoIDParameter );
elements[0] = &m_fBlockInfoIDParameter;
elements[1] = &m_fBlockInfoDescriptionParameter;
m_fBlockInfoFunction.SetDataItems(12, 2, elements);
elements[0] = &m_fBlockInfoIDParameter;
m_fBlockInfoFunction.SetDataItems(1, 1, elements);
AddFunction( &m_fBlockInfoFunction );
m_signalQualityFunction.FunctionID( 0xC02 );
m_signalQualityFunction.Notification( true );
m_signalQualityFunction.AutomaticNotification( true );
m_signalQualityFunction.SupportedOperations( 0x9002 );
m_signalQualityDMBSignalQualityParameterSpec.Min( 0 );
m_signalQualityDMBSignalQualityParameterSpec.Max( 5U );
m_signalQualityDMBSignalQualityParameterSpec.Step( 1 );
m_signalQualityDMBSignalQualityParameterSpec.Exponent( 0 );
m_signalQualityDMBSignalQualityParameter.SetValidator( &m_signalQualityDMBSignalQualityParameterSpec );
m_signalQualityDMBSignalQualityParameter.Value( m_signalQualityDMBSignalQualityParameterSpec.Min() );
elements[0] = &m_signalQualityDMBSignalQualityParameter;
m_signalQualityFunction.SetDataItems(12, 1, elements);
AddFunction( &m_signalQualityFunction );
m_tPEGStatusFunction.FunctionID( 0xC03 );
m_tPEGStatusFunction.Notification( true );
m_tPEGStatusFunction.AutomaticNotification( true );
m_tPEGStatusFunction.SupportedOperations( 0x9002 );
m_tPEGStatusParameterSpec.Values( 3, m_tPEGStatusParameterSpecValues );
m_tPEGStatusParameter.SetValidator( &m_tPEGStatusParameterSpec );
m_tPEGStatusParameter.Value( m_tPEGStatusParameterSpecValues[0] );
elements[0] = &m_tPEGStatusParameter;
m_tPEGStatusFunction.SetDataItems(12, 1, elements);
AddFunction( &m_tPEGStatusFunction );
m_tPEGInfoFunction.FunctionID( 0xC04 );
m_tPEGInfoFunction.Notification( true );
m_tPEGInfoFunction.AutomaticNotification( true );
m_tPEGInfoFunction.SupportedOperations( 0x9002 );
m_tPEGInfoRecevieDateParameterSpec.MaxCharacters( 8 );
m_tPEGInfoRecevieTimeParameterSpec.MaxCharacters( 6 );
m_tPEGInfoRecevieTextParameterSpec.MaxCharacters( 255 );
m_tPEGInfoRecevieDateParameter.SetValidator( &m_tPEGInfoRecevieDateParameterSpec );
m_tPEGInfoRecevieTimeParameter.SetValidator( &m_tPEGInfoRecevieTimeParameterSpec );
m_tPEGInfoRecevieTextParameter.SetValidator( &m_tPEGInfoRecevieTextParameterSpec );
elements[0] = &m_tPEGInfoRecevieDateParameter;
elements[1] = &m_tPEGInfoRecevieTimeParameter;
elements[2] = &m_tPEGInfoRecevieTextParameter;
m_tPEGInfoTPEGInfoRecordFixParameter.SetMembers( 3, elements );
m_tPEGInfoParameter.SetRecordFix( m_tPEGInfoTPEGInfoRecordFixParameter );
m_tPEGInfoTPEGInfoRecordIteratorParameter.SetMembers( 0, elements );
m_tPEGInfoParameter.SetRecordIterator( m_tPEGInfoTPEGInfoRecordIteratorParameter );
elements[0] = &m_tPEGInfoParameter;
m_tPEGInfoFunction.SetDataItems(12, 1, elements);
AddFunction( &m_tPEGInfoFunction );
m_dMBStatusFunction.FunctionID( 0xC0B );
m_dMBStatusFunction.Notification( true );
m_dMBStatusFunction.AutomaticNotification( true );
m_dMBStatusFunction.SupportedOperations( 0x9002 );
m_dMBStatusParameterSpec.Values( 2, m_dMBStatusParameterSpecValues );
m_dMBStatusParameter.SetValidator( &m_dMBStatusParameterSpec );
m_dMBStatusParameter.Value( m_dMBStatusParameterSpecValues[0] );
m_dMBStatusCurrentBrowserListLengthParameterSpec.Min( 1 );
m_dMBStatusCurrentBrowserListLengthParameterSpec.Max( 100U );
m_dMBStatusCurrentBrowserListLengthParameterSpec.Step( 1 );
m_dMBStatusCurrentBrowserListLengthParameterSpec.Exponent( 0 );
m_dMBStatusCurrentBrowserListLengthParameter.SetValidator( &m_dMBStatusCurrentBrowserListLengthParameterSpec );
m_dMBStatusCurrentBrowserListLengthParameter.Value( m_dMBStatusCurrentBrowserListLengthParameterSpec.Min() );
elements[0] = &m_dMBStatusParameter;
elements[1] = &m_dMBStatusCurrentBrowserListLengthParameter;
m_dMBStatusFunction.SetDataItems(12, 2, elements);
AddFunction( &m_dMBStatusFunction );
m_tPEGDataRequestFunction.FunctionID( 0xC21 );
m_tPEGDataRequestFunction.Notification( false /*Method can not be admited to the notification*/ );
m_tPEGDataRequestFunction.AutomaticNotification( false /*Method can not be admited to the notification*/ );
m_tPEGDataRequestFunction.SupportedOperations( 0x2640 );
m_tPEGDataRequestFunction.OperationSendFlags( 13, k2l::acs::base::most::CMessageFlags::MOSTHigh() );
m_tPEGDataRequestBlockTypeParameterSpec.Values( 3, m_tPEGDataRequestBlockTypeParameterSpecValues );
m_tPEGDataRequestBlockTypeParameter.SetValidator( &m_tPEGDataRequestBlockTypeParameterSpec );
m_tPEGDataRequestBlockTypeParameter.Value( m_tPEGDataRequestBlockTypeParameterSpecValues[0] );
AddFunction( &m_tPEGDataRequestFunction );
AddFunction( &m_notificationCheckFunction );
AddFunction( &m_notificationFunction );
AddFunction( &m_fktIDsFunction );
NotificationService( &m_notificationFunction );
m_notificationFunction.Update();
m_fktIDsFunction.Update();
return true;
}


/*=============================================================================
 * END OF FILE
 *=============================================================================*/
