/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusText.xml -i dbusTestInterface.h -p CDbusTestInterface
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "DHAVN_IPodAppController_DBusInterface.h"
#include "DHAVN_IPodAppController_CommonVars.h"
/*
 * Implementation of interface class OrgLgeDbusTestInterface
 */

OrgLgeDbusTestInterface::OrgLgeDbusTestInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    LOG_INIT_V2(gIPodAppControllerLogs);
}

OrgLgeDbusTestInterface::~OrgLgeDbusTestInterface()
{
}


