#ifndef DHAVN_IPODCONTROLLER_DBUSADAPTOR_H
#define DHAVN_IPODCONTROLLER_DBUSADAPTOR_H

/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusText.xml -i dbusTestAdaptor.h -a CDbusTestAdaptor
 *

 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.lge.dbusTest
 */
class DbusTestAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.lge.dbusTest")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.lge.dbusTest\">\n"
"    <signal name=\"IpodAppSessionClosed\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"AppId\"/>\n"
"    </signal>\n"
"    <signal name=\"IPodDisconnected\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"ipodNumber\"/>\n"
"    </signal>\n"
"    <method name=\"GetHidPath\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"ipodNumber\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"GetApplicationSessionID\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"AppId\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"SessionID\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DbusTestAdaptor(QObject *parent);
    virtual ~DbusTestAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    qint16 GetApplicationSessionID(const QString &AppId);
    QString GetHidPath(const QString &ipodNumber);
Q_SIGNALS: // SIGNALS
    void IPodDisconnected(const QString& ipodNumber);
    void IpodAppSessionClosed(const QString& ipodNumber, const QString& appId);
};

#endif // DHAVN_IPODCONTROLLER_DBUSADAPTOR_H
