/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusText.xml -i dbusTestAdaptor.h -a CDbusTestAdaptor
 *

 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include <DHAVN_IPodController_DBusAdaptor.h>
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/******************************************************************************
// Function                                            Parameters
// ::
//
// Explanation

// History
// 06-jan-2012      Pawan Gupta                        Added initial implementation
*****************************************************************************/
DbusTestAdaptor::DbusTestAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

/******************************************************************************
// Function                                            Parameters
// ::
//
// Explanation

// History
// 06-jan-2012      Pawan Gupta                        Added initial implementation
*****************************************************************************/
DbusTestAdaptor::~DbusTestAdaptor()
{
    // destructor
}

/******************************************************************************
// Function                                            Parameters
// ::
//
// Explanation

// History
// 06-jan-2012      Pawan Gupta                        Added initial implementation
*****************************************************************************/
qint16 DbusTestAdaptor::GetApplicationSessionID(const QString &AppId)
{
    // handle method call org.lge.dbusTest.GetApplicationSessionID
    qint16 SessionID;
    QMetaObject::invokeMethod(parent(), "GetApplicationSessionID", Q_RETURN_ARG(qint16, SessionID), Q_ARG(QString, AppId));
    return SessionID;
}

/******************************************************************************
// Function                                            Parameters
// ::
//
// Explanation

// History
// 06-jan-2012      Pawan Gupta                        Added initial implementation
*****************************************************************************/
QString DbusTestAdaptor::GetHidPath(const QString &ipodNumber)
{
    // handle method call org.lge.dbusTest.GetHidPath
    QString path;
    QMetaObject::invokeMethod(parent(), "GetHidPath", Q_RETURN_ARG(QString, path), Q_ARG(QString, ipodNumber));
    return path;
}


